# --------------
# -- Settings --
# --------------
exclude: [vendor]

baseurl: ""

url: "https://plattshacks.org/"

# The ability to use custom themes.
style:
  theme: "main"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title: "PlattsHacks | 31 March 2019"
  description: >
    This is the landing page of the Plattburgh hackathon.
  image: "/images/logo.png"

markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
